# Use postgres/posql123 user/password credentials
version: '3.1'

services:
  db:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_PASSWORD: posql123
    ports:
      - 5432:5432
    networks:
      - cenmed-labs
    volumes:
      - dbdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - cenmed-labs

volumes:
  dbdata:
    driver: local

networks:
  cenmed-labs:
    driver: bridge
